[package]
org = "ballerinax"
name = "postgresql"
version = "1.0.1"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/postgresql-native-1.0.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.0.1-20211027-112400-e76209e.jar"

[[platform.java11.dependency]]
path = "./lib/postgresql-42.2.20.jar"
scope = "testOnly"
